version: "3"
services:
  development:
    container_name: ms-onbloarding-user-java-dev
    image: ms-onbloarding-user-java-dev
    hostname: ms-onbloarding-user-java-dev
    labels:
      description: ms-onbloarding-user-java-dev
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /tmp
    volumes:
      - ./:/tmp/
    env_file:
      - ./.env 
    environment:
      JAVA_ENV: "development"
    command: mvn spring-boot:run
    restart: always
    ports:
      - 8080:8080

  production:
    container_name: ms-onbloarding-user-java
    image: ms-onbloarding-user-java
    hostname: ms-onbloarding-user-java
    labels:
      description: ms-onbloarding-user-java
    build: 
      context: ./
      dockerfile: Dockerfile
    working_dir: /data
    env_file:
      - ./.env 
    environment:
      JAVA_ENV: "production"
    restart: always
    ports:
      - 8081:8080  # host:container